spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: shubham
    password: Qwerty@123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  application:
    name: portfolio-tracking-api
